### ISSUE TITLE
Preview markdown

### ISSUE THREAD

**Issue by ayozebarrera** [agamomo/traducciones#1]
Buenas @agamomo 

Buen repositorio antes que nada, me parece interesante.

Sin embargo creo que te ha faltado añadir el formato de markdown (.md) al fichero para poder verlo bien, por lo demás genial.

Y si por casualidad ya lo sabías y no querías ponerlo, borra la incidencia ^^

Saludos crack!

**Comment by agamomo** [comment]
Hola @ayozebarrera Ayo. No lo que pasa es que la quería publicar como [página web automática de GithHub](http://agamomo.github.io/traducciones), que resulta más agradable. De todas maneras lo añado para que nadie tenga que ir a buscarla. Saludos.

**Comment by ayozebarrera** [comment]
Si, me fijé que tenias preparado lo de gh-pages.

No obstante está bien que lo hayas añadido por lo que has dicho. Buen trabajo crack!

**Comment by agamomo** [comment]
:+1:
